/**
 * The booking form's words, per language, before the platform has spoken.
 *
 * These are a salon's. The words that depend on the kind of business —
 * «Записатися» or «Орендувати», «Майстер» or «Авто» — are the platform's, in
 * its availability answer (`words`), the kind's dictionary with the site's
 * own over it; the element hears them and replaces these. A site in a
 * language not here gets English, which the platform's answer then corrects
 * for the words it has.
 */

/** The languages the form carries words in. */
export const LOCALES = Object.freeze(['uk', 'de', 'en', 'ru', 'es', 'it', 'pt', 'fr']);

const BASE = {
  uk: {
    service: 'Послуга', services: 'Послуги', total: 'Разом', pickService: 'Оберіть хоча б одну послугу.', resource: 'Майстер', any: 'Будь-хто', day: 'День', time: 'Час',
    name: "Ім'я", phone: 'Телефон', email: 'Електронна пошта', note: 'Коментар',
    book: 'Записатися', sending: 'Записуємо…', none: 'У цей день вільного часу немає.', noParty: 'Немає вільних місць для такої компанії.',
    pick: 'Оберіть день', confirmed: 'Ви записані.', pending: 'Запис отримано — ми підтвердимо його найближчим часом.',
    pay: 'Оплатити', payNote: 'Час зарезервовано на 30 хвилин. Щоб закріпити його, завершіть оплату.',
    manage: 'Скасувати або перенести запис', telegram: 'Нагадування в Telegram',
    taken: 'Цей час щойно зайняли — оберіть інший.', failed: 'Не вдалося записатися. Спробуйте ще раз або зателефонуйте.',
    back: 'До', length: 'Від {min} до {max} діб.', anyOf: 'Будь-яке вільне — {class}', noneOf: '{class} — немає вільних', notFor: '{who} — не для обраного', notForChosen: '{who} — не для обраного. Оберіть іншого або «{any}».', took: 'Ви берете: {what}',
    party: 'Скільки вас', hours: 'Скільки часу', hourShort: 'год', minuteShort: 'хв', challenge: 'Підтвердіть, що ви не робот, і спробуйте ще раз.', tooMany: 'У вас уже є кілька відкритих записів. Скасуйте один із них або зателефонуйте нам.',
    needContact: 'Вкажіть телефон або пошту, щоб ми могли з вами звʼязатися.', noScript: 'Онлайн-форма працює з увімкненим JavaScript — увімкніть його або зателефонуйте нам.',
  },
  de: {
    service: 'Leistung', services: 'Leistungen', total: 'Zusammen', pickService: 'Bitte mindestens eine Leistung wählen.', resource: 'Bei', any: 'Egal wer', day: 'Tag', time: 'Uhrzeit',
    name: 'Name', phone: 'Telefon', email: 'E-Mail', note: 'Bemerkung',
    book: 'Termin buchen', sending: 'Wird gebucht…', none: 'An diesem Tag ist nichts frei.', noParty: 'Für so viele Personen gibt es keinen freien Platz.',
    pick: 'Wählen Sie einen Tag', confirmed: 'Ihr Termin ist gebucht.', pending: 'Anfrage erhalten — wir bestätigen den Termin in Kürze.',
    pay: 'Jetzt bezahlen', payNote: 'Der Termin ist 30 Minuten reserviert. Schliessen Sie die Zahlung ab, um ihn zu behalten.',
    manage: 'Termin absagen oder verschieben', telegram: 'Erinnerungen per Telegram',
    taken: 'Diese Zeit wurde gerade vergeben — bitte wählen Sie eine andere.', failed: 'Die Buchung hat nicht geklappt. Bitte erneut versuchen oder anrufen.',
    back: 'Bis', length: 'Von {min} bis {max} Nächte.', anyOf: 'Beliebig frei — {class}', noneOf: '{class} — nichts verfügbar', notFor: '{who} — nicht für diese Auswahl', notForChosen: '{who} — nicht für diese Auswahl. Bitte jemand anderen oder «{any}» wählen.', took: 'Sie nehmen: {what}',
    party: 'Wie viele Personen', hours: 'Wie lange', hourShort: 'Std.', minuteShort: 'Min.', challenge: 'Bitte bestätigen Sie, dass Sie kein Roboter sind, und versuchen Sie es erneut.', tooMany: 'Sie haben bereits mehrere offene Termine. Sagen Sie einen ab oder rufen Sie uns an.',
    needContact: 'Bitte Telefon oder E-Mail angeben, damit wir Sie erreichen können.', noScript: 'Für die Online-Buchung ist JavaScript nötig — oder rufen Sie uns an.',
  },
  en: {
    service: 'Service', services: 'Services', total: 'Total', pickService: 'Pick at least one service.', resource: 'With', any: 'Anyone', day: 'Day', time: 'Time',
    name: 'Name', phone: 'Phone', email: 'Email', note: 'Note',
    book: 'Book', sending: 'Booking…', none: 'Nothing is free on that day.', noParty: 'There is no place for a party this large.',
    pick: 'Choose a day', confirmed: 'You are booked.', pending: 'Received — we will confirm shortly.',
    pay: 'Pay now', payNote: 'The time is held for 30 minutes. Complete the payment to keep it.',
    manage: 'Cancel or move the booking', telegram: 'Reminders in Telegram',
    taken: 'That time has just been taken — please choose another.', failed: 'That did not work. Please try again or ring us.',
    back: 'Until', length: 'From {min} to {max} nights.', anyOf: 'Any free — {class}', noneOf: '{class} — none available', notFor: '{who} — not for this choice', notForChosen: '{who} — not for this choice. Pick another, or «{any}».', took: 'You are taking: {what}',
    party: 'How many of you', hours: 'How long', hourShort: 'h', minuteShort: 'min', challenge: 'Please confirm you are not a robot and try again.', tooMany: 'You already have several open bookings. Cancel one, or ring us.',
    needContact: 'Leave a phone number or an email so we can reach you.', noScript: 'Booking online needs JavaScript — or ring us.',
  },
  ru: {
    service: "Услуга",
    services: "Услуги",
    total: "Итого",
    pickService: "Выберите хотя бы одну услугу.",
    resource: "Мастер",
    any: "Любой",
    day: "День",
    time: "Время",
    name: "Имя",
    phone: "Телефон",
    email: "Электронная почта",
    note: "Комментарий",
    book: "Записаться",
    sending: "Записываем…",
    none: "В этот день свободного времени нет.",
    noParty: "Для такой компании свободных мест нет.",
    pick: "Выберите день",
    confirmed: "Вы записаны.",
    pending: "Запись получена — мы подтвердим ее в ближайшее время.",
    pay: "Оплатить",
    payNote: "Время зарезервировано на 30 минут. Чтобы закрепить его, завершите оплату.",
    manage: "Отменить или перенести запись",
    telegram: "Напоминания в Telegram",
    taken: "Это время только что заняли — выберите другое.",
    failed: "Не удалось записаться. Попробуйте еще раз или позвоните.",
    back: "До",
    length: "От {min} до {max} суток.",
    anyOf: "Любой свободный — {class}",
    noneOf: "{class} — свободных нет",
    notFor: "{who} — не для выбранного",
    notForChosen: "{who} — не для выбранного. Выберите другого или «{any}».",
    took: "Вы берете: {what}",
    party: "Сколько вас",
    hours: "На сколько времени",
    hourShort: "ч",
    minuteShort: "мин",
    challenge: "Подтвердите, что вы не робот, и попробуйте еще раз.",
    tooMany: "У вас уже есть несколько открытых записей. Отмените одну из них или позвоните нам.",
    needContact: "Укажите телефон или почту, чтобы мы могли с вами связаться.",
    noScript: "Онлайн-форма работает с включенным JavaScript — включите его или позвоните нам.",
  },
  es: {
    service: "Servicio",
    services: "Servicios",
    total: "Total",
    pickService: "Elija al menos un servicio.",
    resource: "Con",
    any: "Cualquiera",
    day: "Día",
    time: "Hora",
    name: "Nombre",
    phone: "Teléfono",
    email: "Correo electrónico",
    note: "Comentario",
    book: "Reservar",
    sending: "Reservando…",
    none: "Ese día no queda nada libre.",
    noParty: "No hay sitio para un grupo tan grande.",
    pick: "Elija un día",
    confirmed: "Su reserva está hecha.",
    pending: "Recibida: la confirmaremos en breve.",
    pay: "Pagar ahora",
    payNote: "La hora queda retenida 30 minutos. Complete el pago para conservarla.",
    manage: "Cancelar o mover la reserva",
    telegram: "Recordatorios en Telegram",
    taken: "Esa hora acaba de ocuparse; elija otra, por favor.",
    failed: "No ha funcionado. Inténtelo de nuevo o llámenos.",
    back: "Hasta",
    length: "De {min} a {max} noches.",
    anyOf: "Cualquiera libre — {class}",
    noneOf: "{class} — ninguno disponible",
    notFor: "{who} — no para esta elección",
    notForChosen: "{who} — no para esta elección. Elija otro, o «{any}».",
    took: "Se lleva: {what}",
    party: "Cuántos son",
    hours: "Cuánto tiempo",
    hourShort: "h",
    minuteShort: "min",
    challenge: "Confirme que no es un robot e inténtelo de nuevo.",
    tooMany: "Ya tiene varias reservas abiertas. Cancele una o llámenos.",
    needContact: "Deje un teléfono o un correo electrónico para que podamos contactar con usted.",
    noScript: "Para reservar en línea hace falta JavaScript — o llámenos.",
  },
  it: {
    service: "Servizio",
    services: "Servizi",
    total: "Totale",
    pickService: "Scelga almeno un servizio.",
    resource: "Con",
    any: "Chiunque",
    day: "Giorno",
    time: "Orario",
    name: "Nome",
    phone: "Telefono",
    email: "Email",
    note: "Nota",
    book: "Prenota",
    sending: "Prenotazione…",
    none: "Niente di libero in quel giorno.",
    noParty: "Non c'è posto per un gruppo così numeroso.",
    pick: "Scelga un giorno",
    confirmed: "Prenotazione effettuata.",
    pending: "Ricevuta: confermeremo a breve.",
    pay: "Paga ora",
    payNote: "L'orario è tenuto per 30 minuti. Completi il pagamento per mantenerlo.",
    manage: "Annulla o sposta la prenotazione",
    telegram: "Promemoria su Telegram",
    taken: "Questo orario è appena stato preso: ne scelga un altro.",
    failed: "Non ha funzionato. Riprovi o ci chiami.",
    back: "Fino a",
    length: "Da {min} a {max} notti.",
    anyOf: "Uno qualsiasi libero — {class}",
    noneOf: "{class} — nessuno disponibile",
    notFor: "{who} — non per questa scelta",
    notForChosen: "{who} — non per questa scelta. Ne scelga un altro, o «{any}».",
    took: "Sta prendendo: {what}",
    party: "Quante persone",
    hours: "Per quanto tempo",
    hourShort: "h",
    minuteShort: "min",
    challenge: "Confermi di non essere un robot e riprovi.",
    tooMany: "Ha già diverse prenotazioni aperte. Ne annulli una, o ci chiami.",
    needContact: "Lasci un numero di telefono o un'email per poterLa contattare.",
    noScript: "Per prenotare online serve JavaScript: oppure ci chiami.",
  },
  pt: {
    service: "Serviço",
    services: "Serviços",
    total: "Total",
    pickService: "Escolha pelo menos um serviço.",
    resource: "Com",
    any: "Qualquer um",
    day: "Dia",
    time: "Hora",
    name: "Nome",
    phone: "Telefone",
    email: "E-mail",
    note: "Observações",
    book: "Reservar",
    sending: "A reservar…",
    none: "Não há horários livres nesse dia.",
    noParty: "Não há lugar para um grupo tão grande.",
    pick: "Escolha um dia",
    confirmed: "A sua reserva está feita.",
    pending: "Pedido recebido — confirmamos em breve.",
    pay: "Pagar agora",
    payNote: "O horário fica reservado durante 30 minutos. Conclua o pagamento para o manter.",
    manage: "Cancelar ou remarcar a reserva",
    telegram: "Lembretes no Telegram",
    taken: "Esse horário acabou de ser ocupado — escolha outro.",
    failed: "Não foi possível reservar. Tente de novo ou ligue-nos.",
    back: "Até",
    length: "De {min} a {max} noites.",
    anyOf: "Qualquer livre — {class}",
    noneOf: "{class} — nenhum disponível",
    notFor: "{who} — não para esta escolha",
    notForChosen: "{who} — não para esta escolha. Escolha outro ou «{any}».",
    took: "Leva: {what}",
    party: "Quantos são",
    hours: "Quanto tempo",
    hourShort: "h",
    minuteShort: "min",
    challenge: "Confirme que não é um robô e tente de novo.",
    tooMany: "Já tem várias reservas em aberto. Cancele uma ou ligue-nos.",
    needContact: "Deixe um telefone ou um e-mail para podermos contactá-lo.",
    noScript: "Reservar online precisa de JavaScript — ou ligue-nos.",
  },
  fr: {
    service: "Prestation",
    services: "Prestations",
    total: "Total",
    pickService: "Choisissez au moins une prestation.",
    resource: "Avec",
    any: "Sans préférence",
    day: "Jour",
    time: "Heure",
    name: "Nom",
    phone: "Téléphone",
    email: "E-mail",
    note: "Remarque",
    book: "Réserver",
    sending: "Réservation en cours…",
    none: "Rien n’est libre ce jour-là.",
    noParty: "Pas de place pour un groupe de cette taille.",
    pick: "Choisissez un jour",
    confirmed: "Votre réservation est confirmée.",
    pending: "Demande reçue — nous confirmons sous peu.",
    pay: "Payer maintenant",
    payNote: "Le créneau est réservé pendant 30 minutes. Terminez le paiement pour le conserver.",
    manage: "Annuler ou déplacer la réservation",
    telegram: "Rappels dans Telegram",
    taken: "Ce créneau vient d’être pris — veuillez en choisir un autre.",
    failed: "Cela n’a pas fonctionné. Réessayez ou appelez-nous.",
    back: "Jusqu’au",
    length: "De {min} à {max} nuits.",
    anyOf: "N’importe lequel de libre — {class}",
    noneOf: "{class} — aucun disponible",
    notFor: "{who} — pas pour ce choix",
    notForChosen: "{who} — pas pour ce choix. Choisissez-en un autre, ou « {any} ».",
    took: "Vous prenez : {what}",
    party: "Combien êtes-vous",
    hours: "Combien de temps",
    hourShort: "h",
    minuteShort: "min",
    challenge: "Veuillez confirmer que vous n’êtes pas un robot et réessayer.",
    tooMany: "Vous avez déjà plusieurs réservations en cours. Annulez-en une, ou appelez-nous.",
    needContact: "Laissez un numéro de téléphone ou un e-mail pour que nous puissions vous joindre.",
    noScript: "Réserver en ligne nécessite JavaScript — ou appelez-nous.",
  },
};

// A letting is had for days, not at a time: «Час», «вільного часу немає» and
// «Час зарезервовано» are a salon's words.
const DAYS = {
  uk: {
    day: 'Від', pick: 'Оберіть дати',
    time: 'Дні', none: 'Цього дня нічого вільного немає.',
    payNote: 'Ці дні тримаємо за вами 30 хвилин. Щоб закріпити їх, завершіть оплату.',
    taken: 'Ці дні щойно зайняли — оберіть інші.',
  },
  de: {
    day: 'Von', pick: 'Wählen Sie die Tage',
    time: 'Tage', none: 'Ab diesem Tag ist nichts frei.',
    payNote: 'Die Tage sind 30 Minuten für Sie reserviert. Schliessen Sie die Zahlung ab, um sie zu behalten.',
    taken: 'Diese Tage wurden gerade vergeben — bitte wählen Sie andere.',
  },
  en: {
    day: 'From', pick: 'Choose the dates',
    time: 'Days', none: 'Nothing is free from that day.',
    payNote: 'The days are held for 30 minutes. Complete the payment to keep them.',
    taken: 'Those days have just been taken — please choose others.',
  },
  ru: {
    day: "С",
    pick: "Выберите даты",
    time: "Дни",
    none: "С этого дня ничего свободного нет.",
    payNote: "Эти дни держим за вами 30 минут. Чтобы закрепить их, завершите оплату.",
    taken: "Эти дни только что заняли — выберите другие.",
  },
  es: {
    day: "Desde",
    pick: "Elija las fechas",
    time: "Días",
    none: "A partir de ese día no queda nada libre.",
    payNote: "Los días quedan retenidos 30 minutos. Complete el pago para conservarlos.",
    taken: "Esos días acaban de ocuparse; elija otros, por favor.",
  },
  it: {
    day: "Dal",
    pick: "Scelga le date",
    time: "Giorni",
    none: "Niente di libero da quel giorno.",
    payNote: "I giorni sono tenuti per 30 minuti. Completi il pagamento per mantenerli.",
    taken: "Questi giorni sono appena stati presi: ne scelga altri.",
  },
  pt: {
    day: "De",
    pick: "Escolha as datas",
    time: "Dias",
    none: "Não há nada livre a partir desse dia.",
    payNote: "Os dias ficam reservados durante 30 minutos. Conclua o pagamento para os manter.",
    taken: "Esses dias acabaram de ser ocupados — escolha outros.",
  },
  fr: {
    day: "Du",
    pick: "Choisissez les dates",
    time: "Jours",
    none: "Rien n’est libre à partir de ce jour.",
    payNote: "Les jours sont réservés pendant 30 minutes. Terminez le paiement pour les conserver.",
    taken: "Ces jours viennent d’être pris — veuillez en choisir d’autres.",
  },
};

/**
 * The form's words for a language and a scale — the salon's, or a letting
 * business's by the day — as a fresh object the caller may write over.
 *
 * @param {string} locale  `uk`, `de` or `en`; anything else reads as `en`
 * @param {string} [scale] `'daily'` for a business that lets things by the day
 * @returns {Record<string, string>}
 */
export function wordsFor(locale, scale = '') {
  const lang = LOCALES.includes(locale) ? locale : 'en';
  return scale === 'daily' ? { ...BASE[lang], ...DAYS[lang] } : { ...BASE[lang] };
}
